const locales = {
    "en": {
        "title": "My Farm Game",
        "store_title": "Store",
        "seeds_tab": "Seeds",
        "upgrades_tab": "Upgrades",
        "production_tab": "Production",
        "market_title": "Market",
        "reference_title": "Reference",
        "warehouse_title": "Warehouse",
        "field_title": "Field",
        "buildings_title": "Buildings",
        "btn_store": "Store",
        "btn_market": "Market",
        "btn_reference": "Reference",
        "btn_sell_one": "Sell 1",
        "btn_sell_all": "Sell All",
        "btn_sell_amount": "Sell",
        "btn_buy": "Buy",
        "wheat_seed": "wheat seed",
        "carrot_seed": "carrot seed",
        "tomato_seed": "tomato seed",
        "potato_seed": "potato seed",
        "strawberry_seed": "strawberry seed",
        "blueberry_seed": "blueberry seed",
        "wheat": "wheat",
        "carrot": "carrot",
        "tomato": "tomato",
        "potato": "potato",
        "strawberry": "strawberry",
        "blueberry": "blueberry",
        "buy_item": "Buy {icon} {itemName} (${price})",
        "warehouse_item": "{icon} {itemName}: {amount}",
        "market_item_price": "(Price: ${price})",
        "ref_seed_price": "Seed Price:",
        "ref_growth_time": "Growth Time:",
        "ref_yield": "Yield:",
        "ref_market_price": "Market Price:",
        "ref_stages": "Stages:",
        "ref_per_stage": "{time}s per stage",
        "ref_yield_range": "{min} to {max}",
        "alert_select_seed": "Select a seed from the warehouse first!",
        "alert_not_ready_harvest": "Not ready to harvest yet!",
        "alert_no_crop_to_sell": "You don't have any to sell!",
        "alert_not_enough_money": "Not enough money!",
        "orders_title": "Orders",
        "Farmer Joe": "Farmer Joe",
        "Granny Smith": "Granny Smith",
        "Chef Pierre": "Chef Pierre",
        "Rancher Rick": "Rancher Rick",
        "Baker Betty": "Baker Betty",
        "alert_order_expired": "Order from {name} has expired!",
        "alert_order_fulfilled": "Order for {name} fulfilled! You received a bonus.",
        "alert_not_enough_crops": "You don't have enough crops to fulfill this order.",
        "bread": "bread",
        "milk": "milk",
        "bacon": "bacon",
        "sandwich": "sandwich",
        "cereal": "cereal",
        "Bakery": "Bakery",
        "Dairy": "Dairy",
        "Pig Pen": "Pig Pen",
        "Sandwich Shop": "Sandwich Shop",
        "Breakfast Bar": "Breakfast Bar",
        "Bakes bread from grain.": "Bakes bread from grain.",
        "Produces milk from wheat.": "Produces milk from wheat.",
        "Produces bacon from potatoes.": "Produces bacon from potatoes.",
        "Makes delicious sandwiches.": "Makes delicious sandwiches.",
        "Makes healthy cereal.": "Makes healthy cereal.",
        "Juicer": "Juicer",
        "Extracts juice from fruits and vegetables.": "Extracts juice from fruits and vegetables.",
        "Jam Factory": "Jam Factory",
        "Makes delicious jams from berries.": "Makes delicious jams from berries.",
        "tomato_juice": "tomato juice",
        "carrot_juice": "carrot juice",
        "strawberry_jam": "strawberry jam",
        "blueberry_jam": "blueberry jam",
        "production_input": "Input",
        "production_output": "Output",
        "production_time": "Time",
        "production_recipe": "Recipe",
        "btn_start_production": "Start Production",
        "alert_not_enough_ingredients": "Not enough {item} to start production.",
        "alert_production_finished": "Production of {item} finished!",
        "status_producing": "Producing",
        "status_time_left": "{time}s left",
        "btn_activate_auto": "Activate Automation",
        "btn_deactivate_auto": "Deactivate Automation",
        "status_maxed_out": "Maxed Out",
        "status_purchased": "Purchased",
        "alert_max_purchases": "You have reached the maximum number of purchases for this upgrade.",
        "alert_already_purchased": "You have already purchased this upgrade.",
        "alert_no_empty_plots": "No empty plots available to convert!",
        "alert_plot_converted": "An empty plot has been converted to an automated {crop} plot!",
        "upgrade_fertilizer1_name": "Better Fertilizer",
        "upgrade_fertilizer1_desc": "Crops grow 10% faster.",
        "upgrade_fertilizer2_name": "Super Fertilizer",
        "upgrade_fertilizer2_desc": "Crops grow 25% faster in total.",
        "upgrade_compost1_name": "Compost Bin",
        "upgrade_compost1_desc": "Increases all crop yields by 1.",
        "upgrade_negotiation1_name": "Negotiation Skills",
        "upgrade_negotiation1_desc": "Get a 10% discount on all seeds.",
        "upgrade_charm1_name": "Friendly Charm",
        "upgrade_charm1_desc": "Increase all market sale prices by $2.",
        "upgrade_building_automation_name": "Building Automation",
        "upgrade_building_automation_desc": "Allows buildings to be automated.",
        "upgrade_auto_wheat_name": "Automated Wheat Plot",
        "upgrade_auto_wheat_desc": "Converts a free plot to automatically grow wheat.",
        "upgrade_auto_carrot_name": "Automated Carrot Plot",
        "upgrade_auto_carrot_desc": "Converts a free plot to automatically grow carrots.",
        "upgrade_auto_tomato_name": "Automated Tomato Plot",
        "upgrade_auto_tomato_desc": "Converts a free plot to automatically grow tomatoes.",
        "upgrade_auto_potato_name": "Automated Potato Plot",
        "upgrade_auto_potato_desc": "Converts a free plot to automatically grow potatoes.",
        "upgrade_compost2_name": "Advanced Composting",
        "upgrade_compost2_desc": "Further increases all crop yields by 1.",
        "upgrade_negotiation2_name": "Expert Negotiation",
        "upgrade_negotiation2_desc": "Get a further 10% discount on all seeds (20% total).",
        "upgrade_charm2_name": "Irresistible Charm",
        "upgrade_charm2_desc": "Increase all market sale prices by a further $3 ($5 total).",
        "upgrade_auto_strawberry_name": "Automated Strawberry Plot",
        "upgrade_auto_strawberry_desc": "Converts a free plot to automatically grow strawberries.",
        "upgrade_auto_blueberry_name": "Automated Blueberry Plot",
        "upgrade_auto_blueberry_desc": "Converts a free plot to automatically grow blueberries.",
        "level_display": "Level: {level}",
        "alert_level_up": "Congratulations! You've reached level {level}!",
        "alert_farm_expanded": "Your farm has expanded!",
        "level_up_title": "Level {level}!",
        "unlock_farm_expanded": "Your farm has expanded!",
        "unlocks_crops": "New Seeds Unlocked:",
        "unlocks_buildings": "New Buildings Available:",
        "unlocks_upgrades": "New Upgrades Available:",
        "alert_seed_locked": "You have not unlocked this seed yet!",
        "alert_building_locked": "You have not unlocked this building yet!",
        "alert_upgrade_locked": "You have not unlocked this upgrade yet!",
        "confirm_clear_data": "Are you sure you want to clear all your progress? This cannot be undone.",
        "level_up_congrats": "Congratulations! You've reached level {level}.",
        "level_up_max_level": "You've reached level 11, the highest level currently available. Congratulations on mastering the game!"
    },
    "uk": {
        "title": "Моя Ферма",
        "store_title": "Крамниця",
        "seeds_tab": "Насіння",
        "upgrades_tab": "Покращення",
        "production_tab": "Виробництво",
        "market_title": "Ринок",
        "reference_title": "Довідник",
        "warehouse_title": "Склад",
        "field_title": "Поле",
        "buildings_title": "Будівлі",
        "btn_store": "Крамниця",
        "btn_market": "Ринок",
        "btn_reference": "Довідник",
        "btn_sell_one": "Продати 1",
        "btn_sell_all": "Продати все",
        "btn_sell_amount": "Продати",
        "btn_buy": "Купити",
        "wheat_seed": "насіння пшениці",
        "carrot_seed": "насіння моркви",
        "tomato_seed": "насіння томатів",
        "potato_seed": "насіння картоплі",
        "strawberry_seed": "насіння полуниці",
        "blueberry_seed": "насіння чорниці",
        "wheat": "пшениця",
        "carrot": "морква",
        "tomato": "томат",
        "potato": "картопля",
        "strawberry": "полуниця",
        "blueberry": "чорниця",
        "buy_item": "Купити {icon} {itemName} (${price})",
        "warehouse_item": "{icon} {itemName}: {amount}",
        "market_item_price": "(Ціна: ${price})",
        "ref_seed_price": "Ціна насіння:",
        "ref_growth_time": "Час росту:",
        "ref_yield": "Урожай:",
        "ref_market_price": "Ринкова ціна:",
        "ref_stages": "Стадії:",
        "ref_per_stage": "{time}с за стадію",
        "ref_yield_range": "від {min} до {max}",
        "alert_select_seed": "Спочатку виберіть насіння зі складу!",
        "alert_not_ready_harvest": "Ще не готово для збору!",
        "alert_no_crop_to_sell": "У вас немає нічого для продажу!",
        "alert_not_enough_money": "Недостатньо грошей!",
        "orders_title": "Замовлення",
        "Farmer Joe": "Фермер Джо",
        "Granny Smith": "Бабуся Сміт",
        "Chef Pierre": "Шеф-кухар П'єр",
        "Rancher Rick": "Ранчер Рік",
        "Baker Betty": "Пекар Бетті",
        "alert_order_expired": "Замовлення від {name} закінчилося!",
        "alert_order_fulfilled": "Замовлення для {name} виконано! Ви отримали бонус.",
        "alert_not_enough_crops": "У вас недостатньо врожаю для виконання цього замовлення.",
        "bread": "хліб",
        "milk": "молоко",
        "bacon": "бекон",
        "sandwich": "сендвіч",
        "cereal": "пластівці",
        "Bakery": "Пекарня",
        "Dairy": "Молокозавод",
        "Pig Pen": "Свинарник",
        "Sandwich Shop": "Сендвічна",
        "Breakfast Bar": "Бар сніданків",
        "Bakes bread from grain.": "Випікає хліб із зерна.",
        "Produces milk from wheat.": "Виробляє молоко з пшениці.",
        "Produces bacon from potatoes.": "Виробляє бекон з картоплі.",
        "Makes delicious sandwiches.": "Робить смачні сендвічі.",
        "Makes healthy cereal.": "Робить корисні пластівці.",
        "Juicer": "Соковижималка",
        "Extracts juice from fruits and vegetables.": "Вичавлює сік з фруктів та овочів.",
        "Jam Factory": "Фабрика джему",
        "Makes delicious jams from berries.": "Робить смачні джеми з ягід.",
        "tomato_juice": "томатний сік",
        "carrot_juice": "морквяний сік",
        "strawberry_jam": "полуничний джем",
        "blueberry_jam": "чорничний джем",
        "production_input": "Вхід",
        "production_output": "Вихід",
        "production_time": "Час",
        "production_recipe": "Рецепт",
        "btn_start_production": "Почати виробництво",
        "alert_not_enough_ingredients": "Недостатньо {item} для початку виробництва.",
        "alert_production_finished": "Виробництво {item} завершено!",
        "status_producing": "Виробництво",
        "status_time_left": "залишилось {time}с",
        "btn_activate_auto": "Активувати автоматизацію",
        "btn_deactivate_auto": "Деактивувати автоматизацію",
        "status_maxed_out": "Максимум",
        "status_purchased": "Придбано",
        "alert_max_purchases": "Ви досягли максимальної кількості покупок для цього покращення.",
        "alert_already_purchased": "Ви вже придбали це покращення.",
        "alert_no_empty_plots": "Немає вільних ділянок для перетворення!",
        "alert_plot_converted": "Вільну ділянку було перетворено на автоматизовану ділянку для {crop}!",
        "upgrade_fertilizer1_name": "Краще добриво",
        "upgrade_fertilizer1_desc": "Врожай росте на 10% швидше.",
        "upgrade_fertilizer2_name": "Супер добриво",
        "upgrade_fertilizer2_desc": "Врожай росте на 25% швидше.",
        "upgrade_compost1_name": "Компостний ящик",
        "upgrade_compost1_desc": "Збільшує врожайність усіх культур на 1.",
        "upgrade_negotiation1_name": "Навички ведення переговорів",
        "upgrade_negotiation1_desc": "Знижка 10% на все насіння.",
        "upgrade_charm1_name": "Дружній шарм",
        "upgrade_charm1_desc": "Збільшує ціни продажу на ринку на $2.",
        "upgrade_building_automation_name": "Автоматизація будівель",
        "upgrade_building_automation_desc": "Дозволяє автоматизувати будівлі.",
        "upgrade_auto_wheat_name": "Автоматизована ділянка пшениці",
        "upgrade_auto_wheat_desc": "Перетворює вільну ділянку на автоматичну для вирощування пшениці.",
        "upgrade_auto_carrot_name": "Автоматизована ділянка моркви",
        "upgrade_auto_carrot_desc": "Перетворює вільну ділянку на автоматичну для вирощування моркви.",
        "upgrade_auto_tomato_name": "Автоматизована ділянка томатів",
        "upgrade_auto_tomato_desc": "Перетворює вільну ділянку на автоматичну для вирощування томатів.",
        "upgrade_auto_potato_name": "Автоматизована ділянка картоплі",
        "upgrade_auto_potato_desc": "Перетворює вільну ділянку на автоматичну для вирощування картоплі.",
        "upgrade_compost2_name": "Покращене компостування",
        "upgrade_compost2_desc": "Додатково збільшує врожайність усіх культур на 1.",
        "upgrade_negotiation2_name": "Експертні переговори",
        "upgrade_negotiation2_desc": "Отримайте додаткову знижку 10% на все насіння (всього 20%).",
        "upgrade_charm2_name": "Непереборний шарм",
        "upgrade_charm2_desc": "Збільште всі ринкові ціни продажу ще на $3 (всього $5).",
        "upgrade_auto_strawberry_name": "Автоматизована ділянка полуниці",
        "upgrade_auto_strawberry_desc": "Перетворює вільну ділянку на автоматичну для вирощування полуниці.",
        "upgrade_auto_blueberry_name": "Автоматизована ділянка чорниці",
        "upgrade_auto_blueberry_desc": "Перетворює вільну ділянку на автоматичну для вирощування чорниці.",
        "level_display": "Рівень: {level}",
        "alert_level_up": "Вітаємо! Ви досягли {level} рівня!",
        "alert_farm_expanded": "Ваша ферма розширилася!",
        "level_up_title": "Рівень {level}!",
        "unlock_farm_expanded": "Ваша ферма розширилася!",
        "unlocks_crops": "Нове насіння розблоковано:",
        "unlocks_buildings": "Нові будівлі доступні:",
        "unlocks_upgrades": "Нові покращення доступні:",
        "alert_seed_locked": "Ви ще не розблокували це насіння!",
        "alert_building_locked": "Ви ще не розблокували цю будівлю!",
        "alert_upgrade_locked": "Ви ще не розблокували це покращення!",
        "confirm_clear_data": "Ви впевнені, що хочете видалити весь свій прогрес? Цю дію неможливо буде скасувати.",
        "level_up_congrats": "Вітаємо! Ви досягли {level} рівня.",
        "level_up_max_level": "Ви досягли 11 рівня, найвищого на даний момент. Вітаємо з освоєнням гри!"
    }
};

let currentLang = 'en';
let translations = locales[currentLang];

export function t(key, options = {}) {
    let text = translations[key] || key;
    for (const option in options) {
        text = text.replace(`{${option}}`, options[option]);
    }
    return text;
}

export function setLanguage(lang) {
    currentLang = lang;
    translations = locales[lang];
}
