const locales = {
    "en": {
        "title": "My Farm Game",
        "store_title": "Store",
        "seeds_tab": "Seeds",
        "upgrades_tab": "Upgrades",
        "production_tab": "Production",
        "market_title": "Market",
        "reference_title": "Reference",
        "ref_crops_tab": "Crops",
        "ref_production_tab": "Production",
        "ref_customers_tab": "Customers",
        "ref_my_upgrades_tab": "My Upgrades",
        "warehouse_title": "Warehouse",
        "field_title": "Field",
        "buildings_title": "Buildings",
        "btn_store": "Store",
        "btn_market": "Market",
        "btn_reference": "Reference",
        "btn_sell_one": "Sell 1",
        "btn_sell_all": "Sell All",
        "btn_sell_amount": "Sell",
        "btn_buy": "Buy",
        "btn_max": "Max",
        "wheat_seed": "wheat seed",
        "carrot_seed": "carrot seed",
        "tomato_seed": "tomato seed",
        "potato_seed": "potato seed",
        "strawberry_seed": "strawberry seed",
        "blueberry_seed": "blueberry seed",
        "wheat": "wheat",
        "carrot": "carrot",
        "tomato": "tomato",
        "potato": "potato",
        "strawberry": "strawberry",
        "blueberry": "blueberry",
        "buy_item": "Buy {icon} {itemName} (${price})",
        "warehouse_item": "{icon} {itemName}: {amount}",
        "market_item_price": "(Price: ${price})",
        "ref_seed_price": "Seed Price",
        "ref_growth_time": "Growth Time",
        "ref_yield": "Yield",
        "ref_market_price": "Market Price",
        "ref_stages": "Stages",
        "ref_per_stage": "{time} per stage",
        "ref_yield_range": "{min} to {max}",
        "ref_cost": "Cost",
        "ref_required_level": "Required Level",
        "ref_current_trust": "Current Trust",
        "alert_select_seed": "Select a seed from the warehouse first!",
        "alert_not_ready_harvest": "Not ready to harvest yet!",
        "alert_no_crop_to_sell": "You don't have any to sell!",
        "alert_not_enough_money": "Not enough money!",
        "orders_title": "Orders",
        "Farmer Joe": "Farmer Joe",
        "Granny Smith": "Granny Smith",
        "Chef Pierre": "Chef Pierre",
        "Rancher Rick": "Rancher Rick",
        "Baker Betty": "Baker Betty",
        "alert_order_expired": "Order from {name} has expired!",
        "alert_order_fulfilled": "Order for {name} fulfilled! You received a bonus.",
        "alert_not_enough_crops": "You don't have enough crops to fulfill this order.",
        "order_wants": "Wants",
        "order_have": "Have",
        "order_reward": "Reward",
        "order_time_left": "Time left",
        "order_trust": "Trust",
        "btn_fulfill": "Fulfill",
        "bonus_growth": "Growth",
        "bonus_yield": "Yield",
        "bonus_seed_discount": "Seed Discount",
        "bonus_market_bonus": "Market Bonus",
        "bonus_npc_bonuses": "NPC Bonuses",
        "bonus_growth_speed": "Growth Speed",
        "bonus_market_prices": "Market Prices",
        "bonus_price": "Price",
        "customer_bonus_yield": "Increases all crop yields.",
        "customer_bonus_growth": "All crops grow faster.",
        "customer_bonus_market": "Increases all market sale prices.",
        "customer_bonus_seeds": "Get a discount on all seeds.",
        "customer_bonus_wheat": "Increases sale price of wheat.",
        "ref_bonus_effect": "Bonus Effect",
        "ref_trust_level": "Trust Level",
        "ref_bonus": "Bonus",
        "bread": "bread",
        "milk": "milk",
        "bacon": "bacon",
        "sandwich": "sandwich",
        "cereal": "cereal",
        "Bakery": "Bakery",
        "Dairy": "Dairy",
        "Pig Pen": "Pig Pen",
        "Sandwich Shop": "Sandwich Shop",
        "Breakfast Bar": "Breakfast Bar",
        "Bakes bread from grain.": "Bakes bread from grain.",
        "Produces milk from wheat.": "Produces milk from wheat.",
        "Produces bacon from potatoes.": "Produces bacon from potatoes.",
        "Makes delicious sandwiches.": "Makes delicious sandwiches.",
        "Makes healthy cereal.": "Makes healthy cereal.",
        "Juicer": "Juicer",
        "Extracts juice from fruits and vegetables.": "Extracts juice from fruits and vegetables.",
        "Jam Factory": "Jam Factory",
        "Makes delicious jams from berries.": "Makes delicious jams from berries.",
        "tomato_juice": "tomato juice",
        "carrot_juice": "carrot juice",
        "strawberry_jam": "strawberry jam",
        "blueberry_jam": "blueberry jam",
        "production_input": "Input",
        "production_output": "Output",
        "production_time": "Time",
        "production_recipe": "Recipe",
        "btn_start_production": "Start Production",
        "alert_not_enough_ingredients": "Not enough {item} to start production.",
        "alert_production_finished": "Production of {item} finished!",
        "status_producing": "Producing",
        "status_time_left": "{time} left",
        "btn_activate_auto": "Activate Automation",
        "btn_deactivate_auto": "Deactivate Automation",
        "status_maxed_out": "Maxed Out",
        "status_purchased": "Purchased",
        "alert_max_purchases": "You have reached the maximum number of purchases for this upgrade.",
        "alert_already_purchased": "You have already purchased this upgrade.",
        "alert_no_empty_plots": "No empty plots available to convert!",
        "alert_plot_converted": "An empty plot has been converted to an automated {crop} plot!",
        "upgrade_fertilizer1_name": "Better Fertilizer",
        "upgrade_fertilizer1_desc": "Crops grow 10% faster.",
        "upgrade_fertilizer2_name": "Super Fertilizer",
        "upgrade_fertilizer2_desc": "Crops grow 25% faster in total.",
        "upgrade_compost1_name": "Compost Bin",
        "upgrade_compost1_desc": "Increases all crop yields by 1.",
        "upgrade_negotiation1_name": "Negotiation Skills",
        "upgrade_negotiation1_desc": "Get a 10% discount on all seeds.",
        "upgrade_charm1_name": "Friendly Charm",
        "upgrade_charm1_desc": "Increase all market sale prices by $2.",
        "upgrade_building_automation_name": "Building Automation",
        "upgrade_building_automation_desc": "Allows buildings to be automated.",
        "upgrade_auto_wheat_name": "Automated Wheat Plot",
        "upgrade_auto_wheat_desc": "Converts a free plot to automatically grow wheat.",
        "upgrade_auto_carrot_name": "Automated Carrot Plot",
        "upgrade_auto_carrot_desc": "Converts a free plot to automatically grow carrots.",
        "upgrade_auto_tomato_name": "Automated Tomato Plot",
        "upgrade_auto_tomato_desc": "Converts a free plot to automatically grow tomatoes.",
        "upgrade_auto_potato_name": "Automated Potato Plot",
        "upgrade_auto_potato_desc": "Converts a free plot to automatically grow potatoes.",
        "upgrade_compost2_name": "Advanced Composting",
        "upgrade_compost2_desc": "Further increases all crop yields by 1.",
        "upgrade_negotiation2_name": "Expert Negotiation",
        "upgrade_negotiation2_desc": "Get a further 10% discount on all seeds (20% total).",
        "upgrade_charm2_name": "Irresistible Charm",
        "upgrade_charm2_desc": "Increase all market sale prices by a further $3 ($5 total).",
        "upgrade_auto_strawberry_name": "Automated Strawberry Plot",
        "upgrade_auto_strawberry_desc": "Converts a free plot to automatically grow strawberries.",
        "upgrade_auto_blueberry_name": "Automated Blueberry Plot",
        "upgrade_auto_blueberry_desc": "Converts a free plot to automatically grow blueberries.",
        "level_display": "Level: {level}",
        "alert_level_up": "Congratulations! You've reached level {level}!",
        "alert_farm_expanded": "Your farm has expanded!",
        "level_up_title": "Level {level}!",
        "unlock_farm_expanded": "Your farm has expanded!",
        "unlocks_crops": "New Seeds Unlocked:",
        "btn_clear_data": "Clear Progress",
        "unlocks_buildings": "New Buildings Available:",
        "unlocks_upgrades": "New Upgrades Available:",
        "alert_seed_locked": "You have not unlocked this seed yet!",
        "alert_building_locked": "You have not unlocked this building yet!",
        "alert_upgrade_locked": "You have not unlocked this upgrade yet!",
        "confirm_clear_data": "Are you sure you want to clear all your progress? This cannot be undone.",
        "level_up_congrats": "Congratulations! You've reached level {level}.",
        "level_up_max_level": "You've reached level 11, the highest level currently available. Congratulations on mastering the game!",
        "upgrade_negotiation3_name": "Master Negotiator",
        "upgrade_negotiation3_desc": "Get a further 15% discount on all seeds (35% total).",
        "upgrade_charm3_name": "Legendary Charisma",
        "upgrade_charm3_desc": "Increase all market sale prices by a further $5 ($10 total).",
        "upgrade_fertilizer3_name": "Miracle-Gro",
        "upgrade_fertilizer3_desc": "Crops grow 30% faster in total.",
        "Research Lab": "Research Lab",
        "Unlocks powerful, repeatable upgrades.": "Unlocks powerful, repeatable upgrades.",
        "upgrade_research_yield_name": "Advanced Yield Research",
        "upgrade_research_yield_desc": "Permanently increases all crop yields by 1.",
        "upgrade_research_growth_name": "Growth Hormone Research",
        "upgrade_research_growth_desc": "Permanently increases crop growth speed by 5%.",
        "upgrade_research_market_name": "Market Analysis Research",
        "upgrade_research_market_desc": "Permanently increases all market sale prices by $1.",
        "alert_building_required": "You must construct the {building} to purchase this upgrade.",
        "alert_not_enough_research_points": "Not enough research points!",
        "research_points": "research points",
        "Produces Research Points to unlock powerful, repeatable upgrades.": "Produces Research Points to unlock powerful, repeatable upgrades.",

        "upgrade_prod_speed1_name": "Efficient Machinery",
        "upgrade_prod_speed1_desc": "Increases production speed by 10%.",
        "upgrade_prod_speed2_name": "Assembly Lines",
        "upgrade_prod_speed2_desc": "Increases production speed by a further 15% (25% total).",
        "upgrade_prod_speed3_name": "Automation",
        "upgrade_prod_speed3_desc": "Increases production speed by a further 20% (45% total).",
        "upgrade_prod_speed4_name": "Robotics",
        "upgrade_prod_speed4_desc": "Increases production speed by a further 25% (70% total).",

        "upgrade_prod_eff1_name": "Better Tools",
        "upgrade_prod_eff1_desc": "Increases production efficiency by 10%.",
        "upgrade_prod_eff2_name": "Skilled Labor",
        "upgrade_prod_eff2_desc": "Increases production efficiency by a further 15% (25% total).",
        "upgrade_prod_eff3_name": "Master Craftsmen",
        "upgrade_prod_eff3_desc": "Increases production efficiency by a further 20% (45% total).",
        "upgrade_prod_eff4_name": "Total Quality Management",
        "upgrade_prod_eff4_desc": "Increases production efficiency by a further 25% (70% total).",

        "upgrade_prod_luck1_name": "Good Omen",
        "upgrade_prod_luck1_desc": "Grants a 5% chance for a lucky production outcome (2x items).",
        "upgrade_prod_luck2_name": "Lucky Charm",
        "upgrade_prod_luck2_desc": "Increases lucky chance by a further 10% (15% total).",
        "upgrade_prod_luck3_name": "Leprechaun's Hat",
        "upgrade_prod_luck3_desc": "Increases lucky chance by a further 15% (30% total).",
        "upgrade_prod_luck4_name": "Four-Leaf Clover",
        "upgrade_prod_luck4_desc": "Increases lucky chance by a further 20% (50% total).",

        "upgrade_prod_vol1_name": "Bigger Crates",
        "upgrade_prod_vol1_desc": "Increases production volume by 1.",
        "upgrade_prod_vol2_name": "Expanded Workspace",
        "upgrade_prod_vol2_desc": "Increases production volume by a further 1 (2 total).",
        "upgrade_prod_vol3_name": "Industrial Plant",
        "upgrade_prod_vol3_desc": "Increases production volume by a further 1 (3 total).",
        "upgrade_prod_vol4_name": "Mega Factory",
        "upgrade_prod_vol4_desc": "Increases production volume by a further 1 (4 total).",

        "level_up_max_level": "You've reached level 15, the highest level currently available. Congratulations on mastering the game!",
        "corn_seed": "corn seed",
        "bell_pepper_seed": "bell pepper seed",
        "corn": "corn",
        "bell_pepper": "bell pepper",
        "taco": "taco",
        "salad": "salad",
        "cheese": "cheese",
        "pizza": "pizza",
        "fruit_tart": "fruit tart",

        "taco_stand_name": "Taco Stand",
        "taco_stand_desc": "Makes delicious tacos from corn.",
        "salad_bar_name": "Salad Bar",
        "salad_bar_desc": "Makes healthy salads.",
        "pizzeria_name": "Pizzeria",
        "pizzeria_desc": "Makes delicious pizza.",
        "dessert_shop_name": "Dessert Shop",
        "dessert_shop_desc": "Makes delicious fruit tarts.",

        "upgrade_auto_corn_name": "Automated Corn Plot",
        "upgrade_auto_corn_desc": "Converts a free plot to automatically grow corn.",
        "upgrade_auto_bell_pepper_name": "Automated Bell Pepper Plot",
        "upgrade_auto_bell_pepper_desc": "Converts a free plot to automatically grow bell peppers.",
        "upgrade_fertilizer4_name": "Advanced Fertilizing Techniques",
        "upgrade_fertilizer4_desc": "Crops grow 40% faster in total.",
        "upgrade_compost3_name": "Industrial Composter",
        "upgrade_compost3_desc": "Further increases all crop yields by 1.",
        "upgrade_negotiation4_name": "Corporate Negotiator",
        "upgrade_negotiation4_desc": "Get a further 20% discount on all seeds (55% total).",
        "upgrade_charm4_name": "Celebrity Status",
        "upgrade_charm4_desc": "Increase all market sale prices by a further $7 ($17 total).",

        "upgrade_prod_speed5_name": "Quantum Entanglement",
        "upgrade_prod_speed5_desc": "Increases production speed by a further 30% (100% total).",
        "upgrade_prod_eff5_name": "Perfection",
        "upgrade_prod_eff5_desc": "Increases production efficiency by a further 30% (100% total).",
        "upgrade_prod_luck5_name": "Divine Intervention",
        "upgrade_prod_luck5_desc": "Increases lucky chance by a further 25% (75% total).",
        "upgrade_prod_vol5_name": "Pocket Dimension",
        "upgrade_prod_vol5_desc": "Increases production volume by a further 1 (5 total).",
        "level_label": "Lvl",
        "no_upgrades_purchased": "You haven't purchased any upgrades yet."
    },
    "uk": {
        "title": "Моя Ферма",
        "store_title": "Крамниця",
        "seeds_tab": "Насіння",
        "upgrades_tab": "Покращення",
        "production_tab": "Виробництво",
        "market_title": "Ринок",
        "reference_title": "Довідник",
        "ref_crops_tab": "Врожай",
        "ref_production_tab": "Виробництво",
        "ref_customers_tab": "Клієнти",
        "ref_my_upgrades_tab": "Мої Покращення",
        "warehouse_title": "Склад",
        "field_title": "Поле",
        "buildings_title": "Будівлі",
        "btn_store": "Крамниця",
        "btn_market": "Ринок",
        "btn_reference": "Довідник",
        "btn_sell_one": "Продати 1",
        "btn_sell_all": "Продати все",
        "btn_sell_amount": "Продати",
        "btn_buy": "Купити",
        "btn_max": "Макс",
        "wheat_seed": "насіння пшениці",
        "carrot_seed": "насіння моркви",
        "tomato_seed": "насіння томатів",
        "potato_seed": "насіння картоплі",
        "strawberry_seed": "насіння полуниці",
        "blueberry_seed": "насіння чорниці",
        "wheat": "пшениця",
        "carrot": "морква",
        "tomato": "томат",
        "potato": "картопля",
        "strawberry": "полуниця",
        "blueberry": "чорниця",
        "buy_item": "Купити {icon} {itemName} (${price})",
        "warehouse_item": "{icon} {itemName}: {amount}",
        "market_item_price": "(Ціна: ${price})",
        "ref_seed_price": "Ціна насіння",
        "ref_growth_time": "Час росту",
        "ref_yield": "Урожай",
        "ref_market_price": "Ринкова ціна",
        "ref_stages": "Стадії",
        "ref_per_stage": "{time} за стадію",
        "ref_yield_range": "від {min} до {max}",
        "ref_cost": "Вартість",
        "ref_required_level": "Необхідний рівень",
        "ref_current_trust": "Поточна довіра",
        "alert_select_seed": "Спочатку виберіть насіння зі складу!",
        "alert_not_ready_harvest": "Ще не готово для збору!",
        "alert_no_crop_to_sell": "У вас немає нічого для продажу!",
        "alert_not_enough_money": "Недостатньо грошей!",
        "orders_title": "Замовлення",
        "Farmer Joe": "Фермер Джо",
        "Granny Smith": "Бабуся Сміт",
        "Chef Pierre": "Шеф-кухар П'єр",
        "Rancher Rick": "Ранчер Рік",
        "Baker Betty": "Пекар Бетті",
        "alert_order_expired": "Замовлення від {name} закінчилося!",
        "alert_order_fulfilled": "Замовлення для {name} виконано! Ви отримали бонус.",
        "alert_not_enough_crops": "У вас недостатньо врожаю для виконання цього замовлення.",
        "order_wants": "Бажає",
        "order_have": "Маєте",
        "order_reward": "Нагорода",
        "order_time_left": "Залишилося часу",
        "order_trust": "Довіра",
        "btn_fulfill": "Виконати",
        "bonus_growth": "Зріст",
        "bonus_yield": "Врожайність",
        "bonus_seed_discount": "Знижка на насіння",
        "bonus_market_bonus": "Ринковий бонус",
        "bonus_npc_bonuses": "Бонуси від NPC",
        "bonus_growth_speed": "Швидкість зростання",
        "bonus_market_prices": "Ринкові ціни",
        "bonus_price": "Ціна",
        "customer_bonus_yield": "Збільшує врожайність усіх культур.",
        "customer_bonus_growth": "Усі культури ростуть швидше.",
        "customer_bonus_market": "Збільшує всі ринкові ціни продажу.",
        "customer_bonus_seeds": "Отримайте знижку на все насіння.",
        "customer_bonus_wheat": "Збільшує ціну продажу пшениці.",
        "ref_bonus_effect": "Ефект бонусу",
        "ref_trust_level": "Рівень довіри",
        "ref_bonus": "Бонус",
        "bread": "хліб",
        "milk": "молоко",
        "bacon": "бекон",
        "sandwich": "сендвіч",
        "cereal": "пластівці",
        "Bakery": "Пекарня",
        "Dairy": "Молокозавод",
        "Pig Pen": "Свинарник",
        "Sandwich Shop": "Сендвічна",
        "Breakfast Bar": "Бар сніданків",
        "Bakes bread from grain.": "Випікає хліб із зерна.",
        "Produces milk from wheat.": "Виробляє молоко з пшениці.",
        "Produces bacon from potatoes.": "Виробляє бекон з картоплі.",
        "Makes delicious sandwiches.": "Робить смачні сендвічі.",
        "Makes healthy cereal.": "Робить корисні пластівці.",
        "Juicer": "Соковижималка",
        "Extracts juice from fruits and vegetables.": "Вичавлює сік з фруктів та овочів.",
        "Jam Factory": "Фабрика джему",
        "Makes delicious jams from berries.": "Робить смачні джеми з ягід.",
        "tomato_juice": "томатний сік",
        "carrot_juice": "морквяний сік",
        "strawberry_jam": "полуничний джем",
        "blueberry_jam": "чорничний джем",
        "production_input": "Вхід",
        "production_output": "Вихід",
        "production_time": "Час",
        "production_recipe": "Рецепт",
        "btn_start_production": "Почати виробництво",
        "alert_not_enough_ingredients": "Недостатньо {item} для початку виробництва.",
        "alert_production_finished": "Виробництво {item} завершено!",
        "status_producing": "Виробництво",
        "status_time_left": "залишилось {time}",
        "btn_activate_auto": "Активувати автоматизацію",
        "btn_deactivate_auto": "Деактивувати автоматизацію",
        "status_maxed_out": "Максимум",
        "status_purchased": "Придбано",
        "alert_max_purchases": "Ви досягли максимальної кількості покупок для цього покращення.",
        "alert_already_purchased": "Ви вже придбали це покращення.",
        "alert_no_empty_plots": "Немає вільних ділянок для перетворення!",
        "alert_plot_converted": "Вільну ділянку було перетворено на автоматизовану ділянку для {crop}!",
        "upgrade_fertilizer1_name": "Краще добриво",
        "upgrade_fertilizer1_desc": "Врожай росте на 10% швидше.",
        "upgrade_fertilizer2_name": "Супер добриво",
        "upgrade_fertilizer2_desc": "Врожай росте на 25% швидше.",
        "upgrade_compost1_name": "Компостний ящик",
        "upgrade_compost1_desc": "Збільшує врожайність усіх культур на 1.",
        "upgrade_negotiation1_name": "Навички ведення переговорів",
        "upgrade_negotiation1_desc": "Знижка 10% на все насіння.",
        "upgrade_charm1_name": "Дружній шарм",
        "upgrade_charm1_desc": "Збільшує ціни продажу на ринку на $2.",
        "upgrade_building_automation_name": "Автоматизація будівель",
        "upgrade_building_automation_desc": "Дозволяє автоматизувати будівлі.",
        "upgrade_auto_wheat_name": "Автоматизована ділянка пшениці",
        "upgrade_auto_wheat_desc": "Перетворює вільну ділянку на автоматичну для вирощування пшениці.",
        "upgrade_auto_carrot_name": "Автоматизована ділянка моркви",
        "upgrade_auto_carrot_desc": "Перетворює вільну ділянку на автоматичну для вирощування моркви.",
        "upgrade_auto_tomato_name": "Автоматизована ділянка томатів",
        "upgrade_auto_tomato_desc": "Перетворює вільну ділянку на автоматичну для вирощування томатів.",
        "upgrade_auto_potato_name": "Автоматизована ділянка картоплі",
        "upgrade_auto_potato_desc": "Перетворює вільну ділянку на автоматичну для вирощування картоплі.",
        "upgrade_compost2_name": "Покращене компостування",
        "upgrade_compost2_desc": "Додатково збільшує врожайність усіх культур на 1.",
        "upgrade_negotiation2_name": "Експертні переговори",
        "upgrade_negotiation2_desc": "Отримайте додаткову знижку 10% на все насіння (всього 20%).",
        "upgrade_charm2_name": "Непереборний шарм",
        "upgrade_charm2_desc": "Збільште всі ринкові ціни продажу ще на $3 (всього $5).",
        "upgrade_auto_strawberry_name": "Автоматизована ділянка полуниці",
        "upgrade_auto_strawberry_desc": "Перетворює вільну ділянку на автоматичну для вирощування полуниці.",
        "upgrade_auto_blueberry_name": "Автоматизована ділянка чорниці",
        "upgrade_auto_blueberry_desc": "Перетворює вільну ділянку на автоматичну для вирощування чорниці.",
        "level_display": "Рівень: {level}",
        "alert_level_up": "Вітаємо! Ви досягли {level} рівня!",
        "alert_farm_expanded": "Ваша ферма розширилася!",
        "level_up_title": "Рівень {level}!",
        "unlock_farm_expanded": "Ваша ферма розширилася!",
        "unlocks_crops": "Нове насіння розблоковано:",
        "btn_clear_data": "Очистити прогрес",
        "unlocks_buildings": "Нові будівлі доступні:",
        "unlocks_upgrades": "Нові покращення доступні:",
        "alert_seed_locked": "Ви ще не розблокували це насіння!",
        "alert_building_locked": "Ви ще не розблокували цю будівлю!",
        "alert_upgrade_locked": "Ви ще не розблокували це покращення!",
        "confirm_clear_data": "Ви впевнені, що хочете видалити весь свій прогрес? Цю дію неможливо буде скасувати.",
        "level_up_congrats": "Вітаємо! Ви досягли {level} рівня.",
        "level_up_max_level": "Ви досягли 11 рівня, найвищого на даний момент. Вітаємо з освоєнням гри!",
        "upgrade_negotiation3_name": "Майстер-переговорник",
        "upgrade_negotiation3_desc": "Отримайте додаткову знижку 15% на все насіння (всього 35%).",
        "upgrade_charm3_name": "Легендарна харизма",
        "upgrade_charm3_desc": "Збільште всі ринкові ціни продажу ще на $5 (всього $10).",
        "upgrade_fertilizer3_name": "Диво-ріст",
        "upgrade_fertilizer3_desc": "Врожай росте на 30% швидше.",
        "Research Lab": "Дослідницька лабораторія",
        "Unlocks powerful, repeatable upgrades.": "Розблоковує потужні, повторювані покращення.",
        "upgrade_research_yield_name": "Дослідження врожайності",
        "upgrade_research_yield_desc": "Постійно збільшує врожайність усіх культур на 1.",
        "upgrade_research_growth_name": "Дослідження гормонів росту",
        "upgrade_research_growth_desc": "Постійно збільшує швидкість росту врожаю на 5%.",
        "upgrade_research_market_name": "Дослідження аналізу ринку",
        "upgrade_research_market_desc": "Постійно збільшує всі ринкові ціни продажу на $1.",
        "alert_building_required": "Ви повинні побудувати {building}, щоб придбати це покращення.",
        "alert_not_enough_research_points": "Недостатньо дослідницьких балів!",
        "research_points": "дослідницькі бали",
        "Produces Research Points to unlock powerful, repeatable upgrades.": "Виробляє дослідницькі бали для розблокування потужних, повторюваних покращень.",

        "upgrade_prod_speed1_name": "Ефективне обладнання",
        "upgrade_prod_speed1_desc": "Збільшує швидкість виробництва на 10%.",
        "upgrade_prod_speed2_name": "Складальні лінії",
        "upgrade_prod_speed2_desc": "Збільшує швидкість виробництва ще на 15% (всього 25%).",
        "upgrade_prod_speed3_name": "Автоматизація",
        "upgrade_prod_speed3_desc": "Збільшує швидкість виробництва ще на 20% (всього 45%).",
        "upgrade_prod_speed4_name": "Робототехніка",
        "upgrade_prod_speed4_desc": "Збільшує швидкість виробництва ще на 25% (всього 70%).",

        "upgrade_prod_eff1_name": "Кращі інструменти",
        "upgrade_prod_eff1_desc": "Збільшує ефективність виробництва на 10%.",
        "upgrade_prod_eff2_name": "Кваліфікована праця",
        "upgrade_prod_eff2_desc": "Збільшує ефективність виробництва ще на 15% (всього 25%).",
        "upgrade_prod_eff3_name": "Майстри-ремісники",
        "upgrade_prod_eff3_desc": "Збільшує ефективність виробництва ще на 20% (всього 45%).",
        "upgrade_prod_eff4_name": "Тотальне управління якістю",
        "upgrade_prod_eff4_desc": "Збільшує ефективність виробництва ще на 25% (всього 70%).",

        "upgrade_prod_luck1_name": "Добра прикмета",
        "upgrade_prod_luck1_desc": "Дає 5% шанс на вдалий результат виробництва (x2 предмети).",
        "upgrade_prod_luck2_name": "Щасливий талісман",
        "upgrade_prod_luck2_desc": "Збільшує шанс на удачу ще на 10% (всього 15%).",
        "upgrade_prod_luck3_name": "Капелюх лепрекона",
        "upgrade_prod_luck3_desc": "Збільшує шанс на удачу ще на 15% (всього 30%).",
        "upgrade_prod_luck4_name": "Чотирилисник",
        "upgrade_prod_luck4_desc": "Збільшує шанс на удачу ще на 20% (всього 50%).",

        "upgrade_prod_vol1_name": "Більші ящики",
        "upgrade_prod_vol1_desc": "Збільшує обсяг виробництва на 1.",
        "upgrade_prod_vol2_name": "Розширений робочий простір",
        "upgrade_prod_vol2_desc": "Збільшує обсяг виробництва ще на 1 (всього 2).",
        "upgrade_prod_vol3_name": "Промисловий завод",
        "upgrade_prod_vol3_desc": "Збільшує обсяг виробництва ще на 1 (всього 3).",
        "upgrade_prod_vol4_name": "Мегафабрика",
        "upgrade_prod_vol4_desc": "Збільшує обсяг виробництва ще на 1 (всього 4).",

        "level_up_max_level": "Ви досягли 15 рівня, найвищого на даний момент. Вітаємо з освоєнням гри!",
        "corn_seed": "насіння кукурудзи",
        "bell_pepper_seed": "насіння болгарського перцю",
        "corn": "кукурудза",
        "bell_pepper": "болгарський перець",
        "taco": "тако",
        "salad": "салат",
        "cheese": "сир",
        "pizza": "піца",
        "fruit_tart": "фруктовий тарт",

        "taco_stand_name": "🌮",
        "taco_stand_desc": "Робить смачні тако з кукурудзи.",
        "salad_bar_name": "Салат-бар",
        "salad_bar_desc": "Робить корисні салати.",
        "pizzeria_name": "Піцерія",
        "pizzeria_desc": "Робить смачну піцу.",
        "dessert_shop_name": "Кондитерська",
        "dessert_shop_desc": "Робить смачні фруктові тарти.",

        "upgrade_auto_corn_name": "Автоматизована ділянка кукурудзи",
        "upgrade_auto_corn_desc": "Перетворює вільну ділянку на автоматичну для вирощування кукурудзи.",
        "upgrade_auto_bell_pepper_name": "Автоматизована ділянка болгарського перцю",
        "upgrade_auto_bell_pepper_desc": "Перетворює вільну ділянку на автоматичну для вирощування болгарського перцю.",
        "upgrade_fertilizer4_name": "Передові технології добрив",
        "upgrade_fertilizer4_desc": "Врожай росте на 40% швидше.",
        "upgrade_compost3_name": "Промисловий компостер",
        "upgrade_compost3_desc": "Додатково збільшує врожайність усіх культур на 1.",
        "upgrade_negotiation4_name": "Корпоративний переговорник",
        "upgrade_negotiation4_desc": "Отримайте додаткову знижку 20% на все насіння (всього 55%).",
        "upgrade_charm4_name": "Статус знаменитості",
        "upgrade_charm4_desc": "Збільште всі ринкові ціни продажу ще на $7 (всього $17).",

        "upgrade_prod_speed5_name": "Квантова заплутаність",
        "upgrade_prod_speed5_desc": "Збільшує швидкість виробництва ще на 30% (всього 100%).",
        "upgrade_prod_eff5_name": "Досконалість",
        "upgrade_prod_eff5_desc": "Збільшує ефективність виробництва ще на 30% (всього 100%).",
        "upgrade_prod_luck5_name": "Божественне втручання",
        "upgrade_prod_luck5_desc": "Збільшує шанс на удачу ще на 25% (всього 75%).",
        "upgrade_prod_vol5_name": "Кишеньковий вимір",
        "upgrade_prod_vol5_desc": "Збільшує обсяг виробництва ще на 1 (всього 5).",
        "level_label": "Рів",
        "no_upgrades_purchased": "Ви ще не придбали жодних покращень."
    }
};

let currentLang = 'en';
let translations = locales[currentLang];

export function t(key, options = {}) {
    let text = translations[key] || key;
    for (const option in options) {
        text = text.replace(`{${option}}`, options[option]);
    }
    return text;
}

export function setLanguage(lang) {
    currentLang = lang;
    translations = locales[lang];
}
